
export const APPOINTMENTS_DATA = [
  {
    id: "1",
    dateTime: { date: "Apr 18, 2026", time: "10:00 AM · 45 mins" },
    client: "James Thornton",
    agent: "Robert Taylor",
    type: "Will Review",
    format: "Zoom",
    status: "Confirmed",
  },
  {
    id: "2",
    dateTime: { date: "Apr 18, 2026", time: "11:00 AM · 30 mins" },
    client: "James Thornton",
    agent: "David Clarke",
    type: "Asset Discussion",
    format: "Zoom",
    status: "Confirmed",
  },
  {
    id: "3",
    dateTime: { date: "Apr 18, 2026", time: "12:00 PM · 60 mins" },
    client: "Sarah Mitchell",
    agent: "Emma Williams",
    type: "Initial Consultation",
    format: "Zoom",
    status: "Pending",
  },
  {
    id: "4",
    dateTime: { date: "Apr 18, 2026", time: "01:00 PM · 45 mins" },
    client: "James Thornton",
    agent: "Michael Brown",
    type: "Will Drafting",
    format: "Zoom",
    status: "Confirmed",
  },
  {
    id: "5",
    dateTime: { date: "Apr 18, 2026", time: "02:00 PM · 30 mins" },
    client: "Emily Clarke",
    agent: "Jennifer Scott",
    type: "Will Review",
    format: "Phone",
    status: "Cancel",
  },
  {
    id: "6",
    dateTime: { date: "Apr 18, 2026", time: "03:00 PM · 45 mins" },
    client: "Sarah Mitchell",
    agent: "Robert Taylor",
    type: "Will Drafting",
    format: "Zoom",
    status: "Confirmed",
  },
  {
    id: "7",
    dateTime: { date: "Apr 18, 2026", time: "04:00 PM · 45 mins" },
    client: "Emily Clarke",
    agent: "Emma Williams",
    type: "Will Review",
    format: "Zoom",
    status: "Pending",
  },
  {
    id: "8",
    dateTime: { date: "Apr 18, 2026", time: "05:00 PM · 60 mins" },
    client: "James Thornton",
    agent: "Michael Brown",
    type: "Initial Consultation",
    format: "Zoom",
    status: "Confirmed",
  },

  {
    id: "9",
    dateTime: { date: "Apr 19, 2026", time: "09:00 AM · 45 mins" },
    client: "Robert Adams",
    agent: "Sarah Mitchell",
    type: "Estate Planning",
    format: "Zoom",
    status: "Confirmed",
  },
  {
    id: "10",
    dateTime: { date: "Apr 19, 2026", time: "10:30 AM · 30 mins" },
    client: "Patricia Hale",
    agent: "Emily Clarke",
    type: "Will Review",
    format: "Phone",
    status: "Pending",
  },
  {
    id: "11",
    dateTime: { date: "Apr 19, 2026", time: "11:30 AM · 60 mins" },
    client: "Thomas Wright",
    agent: "David Clarke",
    type: "Asset Discussion",
    format: "Zoom",
    status: "Confirmed",
  },
  {
    id: "12",
    dateTime: { date: "Apr 19, 2026", time: "01:00 PM · 45 mins" },
    client: "Olivia Green",
    agent: "Robert Taylor",
    type: "Will Drafting",
    format: "Zoom",
    status: "Confirmed",
  },
  {
    id: "13",
    dateTime: { date: "Apr 19, 2026", time: "02:30 PM · 30 mins" },
    client: "Daniel Lee",
    agent: "Emma Williams",
    type: "Initial Consultation",
    format: "Phone",
    status: "Pending",
  },
  {
    id: "14",
    dateTime: { date: "Apr 19, 2026", time: "03:30 PM · 45 mins" },
    client: "Sophia Turner",
    agent: "Michael Brown",
    type: "Will Review",
    format: "Zoom",
    status: "Cancel",
  },
  {
    id: "15",
    dateTime: { date: "Apr 19, 2026", time: "04:30 PM · 45 mins" },
    client: "William Harris",
    agent: "Jennifer Scott",
    type: "Estate Planning",
    format: "Zoom",
    status: "Confirmed",
  },

  {
    id: "16",
    dateTime: { date: "Apr 20, 2026", time: "09:00 AM · 60 mins" },
    client: "Grace Walker",
    agent: "Sarah Mitchell",
    type: "Asset Discussion",
    format: "Zoom",
    status: "Pending",
  },
  {
    id: "17",
    dateTime: { date: "Apr 20, 2026", time: "10:30 AM · 45 mins" },
    client: "Henry Young",
    agent: "David Clarke",
    type: "Will Drafting",
    format: "Zoom",
    status: "Confirmed",
  },
  {
    id: "18",
    dateTime: { date: "Apr 20, 2026", time: "11:30 AM · 30 mins" },
    client: "Ava King",
    agent: "Robert Taylor",
    type: "Will Review",
    format: "Phone",
    status: "Confirmed",
  },
  {
    id: "19",
    dateTime: { date: "Apr 20, 2026", time: "01:00 PM · 45 mins" },
    client: "Lucas Hall",
    agent: "Emma Williams",
    type: "Initial Consultation",
    format: "Zoom",
    status: "Pending",
  },
  {
    id: "20",
    dateTime: { date: "Apr 20, 2026", time: "02:30 PM · 60 mins" },
    client: "Mia Allen",
    agent: "Michael Brown",
    type: "Estate Planning",
    format: "Zoom",
    status: "Confirmed",
  },
  {
    id: "21",
    dateTime: { date: "Apr 20, 2026", time: "04:00 PM · 45 mins" },
    client: "Ethan Baker",
    agent: "Jennifer Scott",
    type: "Will Review",
    format: "Phone",
    status: "Cancel",
  },
  {
    id: "22",
    dateTime: { date: "Apr 20, 2026", time: "05:00 PM · 45 mins" },
    client: "Charlotte Carter",
    agent: "Sarah Mitchell",
    type: "Asset Discussion",
    format: "Zoom",
    status: "Confirmed",
  },

  {
    id: "23",
    dateTime: { date: "Apr 21, 2026", time: "09:30 AM · 45 mins" },
    client: "Benjamin Evans",
    agent: "David Clarke",
    type: "Will Drafting",
    format: "Zoom",
    status: "Confirmed",
  },
  {
    id: "24",
    dateTime: { date: "Apr 21, 2026", time: "10:30 AM · 30 mins" },
    client: "Amelia Foster",
    agent: "Robert Taylor",
    type: "Will Review",
    format: "Phone",
    status: "Pending",
  },
  {
    id: "25",
    dateTime: { date: "Apr 21, 2026", time: "11:30 AM · 60 mins" },
    client: "Logan Gray",
    agent: "Emma Williams",
    type: "Estate Planning",
    format: "Zoom",
    status: "Confirmed",
  },
  {
    id: "26",
    dateTime: { date: "Apr 21, 2026", time: "01:00 PM · 45 mins" },
    client: "Ella Hughes",
    agent: "Michael Brown",
    type: "Asset Discussion",
    format: "Zoom",
    status: "Cancel",
  },
  {
    id: "27",
    dateTime: { date: "Apr 21, 2026", time: "02:30 PM · 45 mins" },
    client: "Jacob Jenkins",
    agent: "Jennifer Scott",
    type: "Initial Consultation",
    format: "Phone",
    status: "Confirmed",
  },
  {
    id: "28",
    dateTime: { date: "Apr 21, 2026", time: "03:30 PM · 30 mins" },
    client: "Harper Kelly",
    agent: "Sarah Mitchell",
    type: "Will Review",
    format: "Zoom",
    status: "Pending",
  },
  {
    id: "29",
    dateTime: { date: "Apr 21, 2026", time: "04:30 PM · 60 mins" },
    client: "Sebastian Lewis",
    agent: "David Clarke",
    type: "Will Drafting",
    format: "Zoom",
    status: "Confirmed",
  },
  {
    id: "30",
    dateTime: { date: "Apr 21, 2026", time: "05:30 PM · 45 mins" },
    client: "Evelyn Morgan",
    agent: "Robert Taylor",
    type: "Estate Planning",
    format: "Phone",
    status: "Confirmed",
  },
];
