export const ADMIN_CLIENTS_TABLE_DATA = [
  {
    clientName: "Sarah Johnson",
    email: "sarah@example.com",
    assignedAgent: "James Thornton",
    plan: "Basic",
    willStatus: "Complete",
    created: "15 Apr 2026",
    invoiceStatus: "Paid",
  },
  {
    clientName: "Michael Brown",
    email: "michael@example.com",
    assignedAgent: "James Thornton",
    plan: "Standard",
    willStatus: "In Progress",
    created: "11 Apr 2026",
    invoiceStatus: "Unpaid",
  },
  {
    clientName: "Emma Williams",
    email: "emma@example.com",
    assignedAgent: "Sarah Mitchell",
    plan: "Premium",
    willStatus: "Complete",
    created: "08 Apr 2026",
    invoiceStatus: "Pending",
  },
  {
    clientName: "David Clarke",
    email: "david@example.com",
    assignedAgent: "James Thornton",
    plan: "Basic",
    willStatus: "Start",
    created: "03 Apr 2026",
    invoiceStatus: "Paid",
  },
  {
    clientName: "Jennifer Scott",
    email: "jennifer@example.com",
    assignedAgent: "Emily Clarke",
    plan: "Premium",
    willStatus: "In Progress",
    created: "15 Mar 2026",
    invoiceStatus: "Overdue",
  },
  {
    clientName: "Robert Adams",
    email: "robert@example.com",
    assignedAgent: "Sarah Mitchell",
    plan: "Basic",
    willStatus: "Complete",
    created: "28 Feb 2026",
    invoiceStatus: "Paid",
  },
  {
    clientName: "Patricia Hale",
    email: "patricia@example.com",
    assignedAgent: "Emily Clarke",
    plan: "Basic",
    willStatus: "In Progress",
    created: "24 Feb 2026",
    invoiceStatus: "Unpaid",
  },
  {
    clientName: "Thomas Wright",
    email: "thomas@example.com",
    assignedAgent: "James Thornton",
    plan: "Standard",
    willStatus: "Complete",
    created: "18 Feb 2026",
    invoiceStatus: "Paid",
  },
  {
    clientName: "Olivia Green",
    email: "olivia@example.com",
    assignedAgent: "Sarah Mitchell",
    plan: "Premium",
    willStatus: "Start",
    created: "10 Feb 2026",
    invoiceStatus: "Pending",
  },
  {
    clientName: "Daniel Lee",
    email: "daniel@example.com",
    assignedAgent: "Emily Clarke",
    plan: "Basic",
    willStatus: "Complete",
    created: "05 Feb 2026",
    invoiceStatus: "Paid",
  },
  {
    clientName: "Sophia Turner",
    email: "sophia@example.com",
    assignedAgent: "James Thornton",
    plan: "Standard",
    willStatus: "In Progress",
    created: "01 Feb 2026",
    invoiceStatus: "Overdue",
  },
  {
    clientName: "William Harris",
    email: "william@example.com",
    assignedAgent: "Sarah Mitchell",
    plan: "Premium",
    willStatus: "Complete",
    created: "29 Jan 2026",
    invoiceStatus: "Paid",
  },
  {
    clientName: "Grace Walker",
    email: "grace@example.com",
    assignedAgent: "Emily Clarke",
    plan: "Basic",
    willStatus: "Start",
    created: "22 Jan 2026",
    invoiceStatus: "Unpaid",
  },
  {
    clientName: "Henry Young",
    email: "henry@example.com",
    assignedAgent: "James Thornton",
    plan: "Standard",
    willStatus: "Complete",
    created: "18 Jan 2026",
    invoiceStatus: "Paid",
  },
  {
    clientName: "Ava King",
    email: "ava@example.com",
    assignedAgent: "Sarah Mitchell",
    plan: "Premium",
    willStatus: "In Progress",
    created: "12 Jan 2026",
    invoiceStatus: "Pending",
  },
  {
    clientName: "Lucas Hall",
    email: "lucas@example.com",
    assignedAgent: "Emily Clarke",
    plan: "Basic",
    willStatus: "Complete",
    created: "05 Jan 2026",
    invoiceStatus: "Paid",
  },
  {
    clientName: "Mia Allen",
    email: "mia@example.com",
    assignedAgent: "James Thornton",
    plan: "Standard",
    willStatus: "Start",
    created: "29 Dec 2025",
    invoiceStatus: "Overdue",
  },
  {
    clientName: "Ethan Baker",
    email: "ethan@example.com",
    assignedAgent: "Sarah Mitchell",
    plan: "Basic",
    willStatus: "Complete",
    created: "22 Dec 2025",
    invoiceStatus: "Paid",
  },
  {
    clientName: "Charlotte Carter",
    email: "charlotte@example.com",
    assignedAgent: "Emily Clarke",
    plan: "Premium",
    willStatus: "In Progress",
    created: "15 Dec 2025",
    invoiceStatus: "Pending",
  },
  {
    clientName: "Benjamin Evans",
    email: "benjamin@example.com",
    assignedAgent: "James Thornton",
    plan: "Basic",
    willStatus: "Complete",
    created: "08 Dec 2025",
    invoiceStatus: "Paid",
  },
  {
    clientName: "Amelia Foster",
    email: "amelia@example.com",
    assignedAgent: "Sarah Mitchell",
    plan: "Standard",
    willStatus: "Start",
    created: "01 Dec 2025",
    invoiceStatus: "Unpaid",
  },
  {
    clientName: "Logan Gray",
    email: "logan@example.com",
    assignedAgent: "Emily Clarke",
    plan: "Premium",
    willStatus: "Complete",
    created: "25 Nov 2025",
    invoiceStatus: "Paid",
  },
  {
    clientName: "Ella Hughes",
    email: "ella@example.com",
    assignedAgent: "James Thornton",
    plan: "Basic",
    willStatus: "In Progress",
    created: "19 Nov 2025",
    invoiceStatus: "Overdue",
  },
  {
    clientName: "Jacob Jenkins",
    email: "jacob@example.com",
    assignedAgent: "Sarah Mitchell",
    plan: "Standard",
    willStatus: "Complete",
    created: "12 Nov 2025",
    invoiceStatus: "Paid",
  },
  {
    clientName: "Harper Kelly",
    email: "harper@example.com",
    assignedAgent: "Emily Clarke",
    plan: "Premium",
    willStatus: "Start",
    created: "06 Nov 2025",
    invoiceStatus: "Pending",
  },
  {
    clientName: "Sebastian Lewis",
    email: "sebastian@example.com",
    assignedAgent: "James Thornton",
    plan: "Basic",
    willStatus: "Complete",
    created: "30 Oct 2025",
    invoiceStatus: "Paid",
  },
  {
    clientName: "Evelyn Morgan",
    email: "evelyn@example.com",
    assignedAgent: "Sarah Mitchell",
    plan: "Premium",
    willStatus: "In Progress",
    created: "24 Oct 2025",
    invoiceStatus: "Unpaid",
  },
  {
    clientName: "Jack Nelson",
    email: "jack@example.com",
    assignedAgent: "Emily Clarke",
    plan: "Standard",
    willStatus: "Complete",
    created: "18 Oct 2025",
    invoiceStatus: "Paid",
  },
  {
    clientName: "Scarlett Owens",
    email: "scarlett@example.com",
    assignedAgent: "James Thornton",
    plan: "Basic",
    willStatus: "Start",
    created: "11 Oct 2025",
    invoiceStatus: "Pending",
  },
  {
    clientName: "Matthew Perry",
    email: "matthew@example.com",
    assignedAgent: "Sarah Mitchell",
    plan: "Premium",
    willStatus: "Complete",
    created: "04 Oct 2025",
    invoiceStatus: "Paid",
  },
];