import { AgentStatus } from "@/components/organisms/dashboard/admin/overview/adminRecentTableConfig";

export interface AgentTableItem {
  id: number;
  agentName: string;
  email: string;
  agents: number;
  wills: number;
  status: AgentStatus;
}

export interface ClientTableItem {
  id: number;
  clientName: string;
  email: string;
  clients: number;
  wills: number;
  status: AgentStatus;
}

export const CLIENT_TABLE_DATA: ClientTableItem[] = [
  {
    id: 1,
    clientName: "James Thornton",
    email: "james@inheritx.com",
    clients: 24,
    wills: 18,
    status: "Active",
  },
  {
    id: 2,
    clientName: "Sarah Mitchell",
    email: "sarah.m@inheritx.com",
    clients: 18,
    wills: 15,
    status: "Active",
  },
  {
    id: 3,
    clientName: "Robert Clarke",
    email: "r.clarke@inheritx.com",
    clients: 5,
    wills: 2,
    status: "Pending",
  },
  {
    id: 4,
    clientName: "Emily Watson",
    email: "emily@inheritx.com",
    clients: 31,
    wills: 22,
    status: "Active",
  },
  {
    id: 5,
    clientName: "Daniel Brooks",
    email: "daniel@inheritx.com",
    clients: 12,
    wills: 7,
    status: "Pending",
  },
  {
    id: 6,
    clientName: "Olivia Bennett",
    email: "olivia@inheritx.com",
    clients: 27,
    wills: 21,
    status: "Active",
  },
  {
    id: 7,
    clientName: "Michael Reed",
    email: "michael@inheritx.com",
    clients: 9,
    wills: 4,
    status: "Inactive",
  },
  {
    id: 8,
    clientName: "Sophia Turner",
    email: "sophia@inheritx.com",
    clients: 15,
    wills: 10,
    status: "Active",
  },
  {
    id: 9,
    clientName: "William Harris",
    email: "william@inheritx.com",
    clients: 22,
    wills: 17,
    status: "Pending",
  },
  {
    id: 10,
    clientName: "Ava Cooper",
    email: "ava@inheritx.com",
    clients: 14,
    wills: 11,
    status: "Active",
  },
  {
    id: 11,
    clientName: "Benjamin Scott",
    email: "benjamin@inheritx.com",
    clients: 8,
    wills: 3,
    status: "Inactive",
  },
  {
    id: 12,
    clientName: "Charlotte Evans",
    email: "charlotte@inheritx.com",
    clients: 19,
    wills: 13,
    status: "Active",
  },
  {
    id: 13,
    clientName: "Henry Walker",
    email: "henry@inheritx.com",
    clients: 11,
    wills: 6,
    status: "Pending",
  },
  {
    id: 14,
    clientName: "Mia Phillips",
    email: "mia@inheritx.com",
    clients: 26,
    wills: 20,
    status: "Active",
  },
  {
    id: 15,
    clientName: "Lucas Green",
    email: "lucas@inheritx.com",
    clients: 7,
    wills: 2,
    status: "Inactive",
  },
  {
    id: 16,
    clientName: "Ella Parker",
    email: "ella@inheritx.com",
    clients: 20,
    wills: 16,
    status: "Active",
  },
  {
    id: 17,
    clientName: "Alexander Hall",
    email: "alex@inheritx.com",
    clients: 13,
    wills: 9,
    status: "Pending",
  },
  {
    id: 18,
    clientName: "Grace Allen",
    email: "grace@inheritx.com",
    clients: 28,
    wills: 24,
    status: "Active",
  },
  {
    id: 19,
    clientName: "Ethan Young",
    email: "ethan@inheritx.com",
    clients: 6,
    wills: 1,
    status: "Inactive",
  },
  {
    id: 20,
    clientName: "Harper King",
    email: "harper@inheritx.com",
    clients: 17,
    wills: 12,
    status: "Active",
  },
];

export const AGENT_TABLE_DATA: AgentTableItem[] = [
  {
    id: 1,
    agentName: "James Thornton",
    email: "james@inheritx.com",
    agents: 24,
    wills: 18,
    status: "Active",
  },
  {
    id: 2,
    agentName: "Sarah Mitchell",
    email: "sarah.m@inheritx.com",
    agents: 18,
    wills: 15,
    status: "Active",
  },
  {
    id: 3,
    agentName: "Robert Clarke",
    email: "r.clarke@inheritx.com",
    agents: 5,
    wills: 2,
    status: "Pending",
  },
  {
    id: 4,
    agentName: "Emily Watson",
    email: "emily@inheritx.com",
    agents: 31,
    wills: 22,
    status: "Active",
  },
  {
    id: 5,
    agentName: "Daniel Brooks",
    email: "daniel@inheritx.com",
    agents: 12,
    wills: 7,
    status: "Pending",
  },
  {
    id: 6,
    agentName: "Olivia Bennett",
    email: "olivia@inheritx.com",
    agents: 27,
    wills: 21,
    status: "Active",
  },
  {
    id: 7,
    agentName: "Michael Reed",
    email: "michael@inheritx.com",
    agents: 9,
    wills: 4,
    status: "Inactive",
  },
  {
    id: 8,
    agentName: "Sophia Turner",
    email: "sophia@inheritx.com",
    agents: 15,
    wills: 10,
    status: "Active",
  },
  {
    id: 9,
    agentName: "William Harris",
    email: "william@inheritx.com",
    agents: 22,
    wills: 17,
    status: "Pending",
  },
  {
    id: 10,
    agentName: "Ava Cooper",
    email: "ava@inheritx.com",
    agents: 14,
    wills: 11,
    status: "Active",
  },
  {
    id: 11,
    agentName: "Benjamin Scott",
    email: "benjamin@inheritx.com",
    agents: 8,
    wills: 3,
    status: "Inactive",
  },
  {
    id: 12,
    agentName: "Charlotte Evans",
    email: "charlotte@inheritx.com",
    agents: 19,
    wills: 13,
    status: "Active",
  },
  {
    id: 13,
    agentName: "Henry Walker",
    email: "henry@inheritx.com",
    agents: 11,
    wills: 6,
    status: "Pending",
  },
  {
    id: 14,
    agentName: "Mia Phillips",
    email: "mia@inheritx.com",
    agents: 26,
    wills: 20,
    status: "Active",
  },
  {
    id: 15,
    agentName: "Lucas Green",
    email: "lucas@inheritx.com",
    agents: 7,
    wills: 2,
    status: "Inactive",
  },
  {
    id: 16,
    agentName: "Ella Parker",
    email: "ella@inheritx.com",
    agents: 20,
    wills: 16,
    status: "Active",
  },
  {
    id: 17,
    agentName: "Alexander Hall",
    email: "alex@inheritx.com",
    agents: 13,
    wills: 9,
    status: "Pending",
  },
  {
    id: 18,
    agentName: "Grace Allen",
    email: "grace@inheritx.com",
    agents: 28,
    wills: 24,
    status: "Active",
  },
  {
    id: 19,
    agentName: "Ethan Young",
    email: "ethan@inheritx.com",
    agents: 6,
    wills: 1,
    status: "Inactive",
  },
  {
    id: 20,
    agentName: "Harper King",
    email: "harper@inheritx.com",
    agents: 17,
    wills: 12,
    status: "Active",
  },
];
