export const appointmentsData = [
  {
    id: 1,
    client: "Sarah Johnson",
    email: "sarah@example.com",
    type: "Initial Consultation",
    date: "2026-04-01",
    status: "Confirmed",
  },
  {
    id: 2,
    client: "Michael Brown",
    type: "Asset Discussion",
    email: "michael@example.com",
    date: "2026-03-28",
    status: "Pending",
  },
  {
    id: 3,
    client: "Emma Williams",
    email: "emma@example.com",
    type: "Will Writing",
    date: "2026-03-25",
    status: "Confirmed",
  },
  {
    id: 4,
    client: "David Clarke",
    email: "david@example.com",
    type: "Sign-off",
    date: "2026-03-20",
    status: "Pending",
  },
  {
    id: 5,
    client: "Jennifer Scott",
    email: "jennifer@example.com",
    type: "Will Writing",
    date: "2026-03-01",
    status: "Confirmed",
  },
  {
    id: 6,
    client: "Robert Adams",
    email: "robert@example.com",
    type: "Initial Consultation",
    date: "2026-02-14",
    status: "Cancelled",
  },
  {
    id: 7,
    client: "Patricia Hale",
    email: "patricia@example.com",
    type: "Asset Discussion",
    date: "2026-02-10",
    status: "Confirmed",
  },
  {
    id: 8,
    client: "James Turner",
    email: "james@example.com",
    type: "Will Writing",
    date: "2026-02-05",
    status: "Pending",
  },
  {
    id: 9,
    client: "Linda Foster",
    email: "linda@example.com",
    type: "Sign-off",
    date: "2026-01-30",
    status: "Confirmed",
  },
  {
    id: 10,
    client: "Charles King",
    email: "charles@example.com",
    type: "Initial Consultation",
    date: "2026-01-25",
    status: "Confirmed",
  },
  {
    id: 11,
    client: "Barbara Wright",
    email: "barbara@example.com",
    type: "Asset Discussion",
    date: "2026-01-20",
    status: "Cancelled",
  },
  {
    id: 12,
    client: "Thomas Hall",
    email: "thomas@example.com",
    type: "Will Writing",
    date: "2026-01-15",
    status: "Confirmed",
  },
  {
    id: 13,
    client: "Susan Allen",
    email: "susan@example.com",
    type: "Sign-off",
    date: "2026-01-10",
    status: "Pending",
  },
  {
    id: 14,
    client: "Christopher Lee",
    email: "chris@example.com",
    type: "Initial Consultation",
    date: "2026-01-05",
    status: "Confirmed",
  },
  {
    id: 15,
    client: "Jessica Young",
    email: "jessica@example.com",
    type: "Asset Discussion",
    date: "2025-12-28",
    status: "Confirmed",
  },
  {
    id: 16,
    client: "Daniel Harris",
    email: "daniel@example.com",
    type: "Will Writing",
    date: "2025-12-20",
    status: "Pending",
  },
  {
    id: 17,
    client: "Margaret Nelson",
    email: "margaret@example.com",
    type: "Sign-off",
    date: "2025-12-15",
    status: "Confirmed",
  },
  {
    id: 18,
    client: "Paul Carter",
    email: "paul@example.com",
    type: "Initial Consultation",
    date: "2025-12-10",
    status: "Cancelled",
  },
  {
    id: 19,
    client: "Nancy Mitchell",
    email: "nancy@example.com",
    type: "Asset Discussion",
    date: "2025-12-05",
    status: "Confirmed",
  },
  {
    id: 20,
    client: "Mark Perez",
    email: "mark@example.com",
    type: "Will Writing",
    date: "2025-11-28",
    status: "Pending",
  },
  {
    id: 21,
    client: "Dorothy Roberts",
    email: "dorothy@example.com",
    type: "Sign-off",
    date: "2025-11-20",
    status: "Confirmed",
  },
  {
    id: 22,
    client: "Steven Evans",
    email: "steven@example.com",
    type: "Initial Consultation",
    date: "2025-11-15",
    status: "Confirmed",
  },
  {
    id: 23,
    client: "Helen Collins",
    email: "helen@example.com",
    type: "Asset Discussion",
    date: "2025-11-10",
    status: "Cancelled",
  },
  {
    id: 24,
    client: "Kenneth Stewart",
    email: "kenneth@example.com",
    type: "Will Writing",
    date: "2025-11-05",
    status: "Confirmed",
  },
  {
    id: 25,
    client: "Sharon Sanchez",
    email: "sharon@example.com",
    type: "Sign-off",
    date: "2025-10-28",
    status: "Pending",
  },
  {
    id: 26,
    client: "George Morris",
    email: "george@example.com",
    type: "Initial Consultation",
    date: "2025-10-20",
    status: "Confirmed",
  },
  {
    id: 27,
    client: "Donna Rogers",
    email: "donna@example.com",
    type: "Asset Discussion",
    date: "2025-10-15",
    status: "Confirmed",
  },
  {
    id: 28,
    client: "Edward Reed",
    email: "edward@example.com",
    type: "Will Writing",
    date: "2025-10-10",
    status: "Pending",
  },
  {
    id: 29,
    client: "Carol Cook",
    email: "carol@example.com",
    type: "Sign-off",
    date: "2025-10-05",
    status: "Confirmed",
  },
  {
    id: 30,
    client: "Brian Morgan",
    email: "brian@example.com",
    type: "Initial Consultation",
    date: "2025-09-28",
    status: "Cancelled",
  },
];
