export const clientData = [
  {
    id: 1,
    name: "Sarah Johnson",
    img:"/avatar.png",
    email: "[email protected]",
    phone: "+44 7700 900001",
    status: "Will Complete",
    will: "PDF Ready",
    invoice: "Paid £249",
    nextAppt: "Apr 4, 2026",
    plan: "Standard",
    actions: ["View Will", "Invoice", "Appt."],
  },
  {
    id: 2,
    name: "David Smith",
     img:"/avatar.png",
    email: "[email protected]",
    phone: "+44 7700 900001",
    status: "In Progress",
    will: "PDF Ready",
    invoice: "Unpaid £149",
    nextAppt: "Apr 26, 2026",
    plan: "Basic",
    actions: ["Edit will", "Invoice", "Appt."],
  },
  {
    id: 3,
    name: "Max Methio",
    img:"/avatar.png",
    email: "[email protected]",
    phone: "+44 7700 900001",
    status: "Will Complete",
    will: "PDF Ready",
    invoice: "Paid £249",
    nextAppt: "Apr 3, 2026",
    plan: "Standard",
    actions: ["View Will", "Invoice", "Appt."],
  },
  {
    id: 4,
    name: "Teo Jun",
    img:"/avatar.png",
    email: "[email protected]",
    phone: "+44 7700 900001",
    status: "Not Started",
    will: "PDF Ready",
    invoice: "Pending",
    nextAppt: "Apr 7, 2026",
    plan: "Premium",
    actions: ["Start Will", "Invoice", "Appt."],
  },
  {
    id: 18,
    name: "Sarah Johnson",
    img:"/avatar.png",
    email: "[EMAIL_ADDRESS]",
    phone: "+44 7700 900001",
    status: "Will Complete",
    will: "PDF Ready",
    invoice: "Paid £249",
    nextAppt: "Apr 4, 2026",
    plan: "Standard",
    actions: ["View Will", "Invoice", "Appt."],
  },
  {
    id: 42,
    name: "David Smith",
     img:"/avatar.png",
    email: "[EMAIL_ADDRESS]",
    phone: "+44 7700 900001",
    status: "In Progress",
    will: "PDF Ready",
    invoice: "Unpaid £149",
    nextAppt: "Apr 26, 2026",
    plan: "Basic",
    actions: ["Edit will", "Invoice", "Appt."],
  },
  {
    id: 5,
    name: "Max Methio",
    img:"/avatar.png",
    email: "[EMAIL_ADDRESS]",
    phone: "+44 7700 900001",
    status: "Will Complete",
    will: "PDF Ready",
    invoice: "Paid £249",
    nextAppt: "Apr 3, 2026",
    plan: "Standard",
    actions: ["View Will", "Invoice", "Appt."],
  },
  {
    id: 6,
    name: "Teo Jun",
    img:"/avatar.png",
    email: "[EMAIL_ADDRESS]",
    phone: "+44 7700 900001",
    status: "Not Started",
    will: "PDF Ready",
    invoice: "Pending",
    nextAppt: "Apr 7, 2026",
    plan: "Premium",
    actions: ["Start Will", "Invoice", "Appt."],
  },
];
