export const estateData = [
  {
    id: 1,
    title: "Will writing",
    desc: "Certified will writers prepare your will with precision - assets, beneficiaries, and all your wishes documented perfectly.",
    badge: "core service",
    imgUrl: "/estateOne.png",
    step: "01",
  },
  {
    id: 2,
    title: "Pdf generation",
    desc: "Your will document is automatically formatted and generated as a professional PDF — instantly available to download.",
    badge: "Automated",
    imgUrl: "/estateTwo.png",
    step: "02",
  },
  {
    id: 3,
    title: "Vault storage",
    desc: "Store your will in our secure digital vault — always protected, always accessible. We keep your most important document safe and sound.",
    badge: "Secure Vault",
    imgUrl: "/estateThree.png",
    step: "03",
  },
  {
    id: 4,
    title: "Appointment booking",
    desc: "Keep your most important documents in our encrypted digital vault - accessible securely whenever you need them. ",
    badge: "256-bit encrypted",
    imgUrl: "/estateFour.png",
    step: "04",
  },
  {
    id: 5,
    title: "Secure Payments",
    desc: "Book consultations with your will writer at your convenience. Flexible slots, instant confirmation sent to both parties. ",
    badge: " Secure payments ",
    imgUrl: "/estateFive.png",
    step: "05",
  },
  {
    id: 6,
    title: "Will revisions",
    desc: "Life changes — and so can your will. Request revisions anytime with your assigned certified will writer.",
    badge: "unlimited",
    imgUrl: "/estateSix.png",
    step: "06",
  },
];